# Generated by Django 3.1.1 on 2020-09-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=100)),
                ('bill_to', models.CharField(max_length=100)),
                ('bill_transactions', models.ManyToManyField(to='Transaction.Transaction')),
            ],
        ),
    ]
