# Generated by Django 3.1.1 on 2020-09-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BatteryModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batterymodel',
            old_name='battery_model_id',
            new_name='battery_model_no',
        ),
    ]
