# Generated by Django 3.1.1 on 2020-09-30 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('BatteryModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_SN', models.CharField(max_length=200)),
                ('battery_longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('battery_latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('battery_status', models.CharField(choices=[('available', 'Available to borrow'), ('borrowed', 'Borrowed by someone'), ('charging', 'Charging in Charger'), ('archived', 'Archived - not available anymore')], default='available', max_length=10)),
                ('battery_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='BatteryModel.batterymodel')),
                ('battery_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
    ]
