# Generated by Django 3.1.1 on 2020-09-30 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=200)),
                ('station_longitude', models.IntegerField()),
                ('station_latitude', models.IntegerField()),
                ('station_name', models.CharField(max_length=20)),
                ('station_city', models.CharField(max_length=20)),
                ('station_state', models.CharField(max_length=20)),
                ('station_country', models.CharField(choices=[('India', 'India'), ('USA', 'US'), ('UK', 'UK')], default='India', max_length=20)),
                ('station_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
    ]
